# Exported from:        http://Sai_Kamal:5516/
# Release version:      25.1.2-610.908
# Date created:         Wed Apr 08 16:52:48 IST 2026

---
apiVersion: xl-release/v1
kind: Import
spec:
  imports:
  - Notifications.yaml
  - Templates.yaml
  - Variables.yaml
