# Exported from:        http://Sai_Kamal:5516/
# Release version:      25.1.2-610.908
# Date created:         Wed Apr 08 14:59:49 IST 2026

---
apiVersion: xl-release/v1
kind: Templates
metadata:
  path: /
  home: tester
spec:
- folderVariables:
  - type: xlrelease.StringVariable
    key: folder.pass
    value: "12345"
  - type: xlrelease.PasswordStringVariable
    key: folder.testpass
    value: !value "xlrelease_PasswordStringVariable_folder_testpass_value"
